In [14]:
import numpy as np
multi_arraya = np.array([[0,1],[2,3],[4,5]])
multi_arrayb = np.array([[0,1,2,3],[4,5,6,7]])

result = multi_arraya @ multi_arrayb
print(result)
max_value = result.max()
print(max_value)


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
